site_name: Gluu Casa Docs Multisite Test
site_description: Documentation for Gluu Casa Multisite Test
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2019, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-casa-prod/blob/3.1.5/testdocs
theme_dir: theme/material
extra:
    version: '3.1.5-test'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- pymdownx.superfences
pages:
- Home: 'index.md'    
- Testpage: 'testpage.md'  
- Administration Guide: 
    - 'Installation': '../../docs/source/administration/installation.md'
    - 'About two-factor authentication': '../../docs/source/administration/2fa-basics.md'
    - 'Admin console': '../../docs/source/administration/admin-console.md'   
    - 'Credentials storage': '../../docs/source/administration/credentials-stored.md'
    - 'Custom branding': '../../docs/source/administration/custom-branding.md'
    # - 'Configuration': '../../docs/source/administration/configuration.md'
    - 'URL path customization': '../../docs/source/administration/change-context-path.md'
    - 'Uninstallation and clean up': '../../docs/source/administration/uninstallation.md'
    - 'FAQ': '../../docs/source/administration/faq.md'
- Developer Guide:
    - 'Intro': '../../docs/source/developer/index.md'
    - 'The basics':
        - 'Architectural details': '../../docs/source/developer/architecture.md'
        - 'Intro to plugin development': '../../docs/source/developer/intro-plugin.md'
        - 'Writing your first plugin': '../../docs/source/developer/writing-first.md'
    - 'Common tasks':
        - 'Working with menus': '../../docs/source/developer/menus.md'
        - 'Adding UI pages': '../../docs/source/developer/ui-pages.md'
        - 'Manipulating LDAP data': '../../docs/source/developer/ldap-data.md'
        - 'Adding REST services': '../../docs/source/developer/rest-services.md'
    - 'Adding authentication methods':
        - 'Introduction': '../../docs/source/developer/authn-methods/index.md'
        - 'Coding authentication logic' : '../../docs/source/developer/authn-methods/authn-logic.md'
        - 'Coding enrollment logic': '../../docs/source/developer/authn-methods/credentials-management.md'
    - 'Other topics':
        - 'Plugin development tips': '../../docs/source/developer/tips-development.md'
        - 'Plugin management internals': '../../docs/source/developer/plugin-management-internals.md'
        - 'FAQ': '../../docs/source/developer/faq.md'
- User Guide : '../../docs/source/user-guide.md'
- Default Plugins:
    - 'Strong Authentication Settings': '../../docs/source/plugins/strong-authn.md'    
    - 'Consent Management': '../../docs/source/plugins/consent-management.md'
    - 'Custom Branding': '../../docs/source/plugins/custom-branding.md'
