site_name: Gluu Casa Docs
site_description: Documentation for Gluu Casa
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2018, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-casa-prod/blob/3.1.4/3.1.4
theme_dir: theme/material
extra:
    version: '3.1.4'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'    
- Administration Guide: 
    - 'Installation': 'administration/installation.md'
    - 'Admin console': 'administration/admin-console.md'   
    - 'Credentials storage': 'administration/credentials-stored.md'
    - 'Custom branding': 'administration/custom-branding.md'
    - 'URL path customization': 'administration/change-context-path.md'
    - 'FAQ': 'administration/faq.md'
- Developer Guide:
    - 'Intro': 'developer/index.md'
    - 'The basics':
        - 'Architectural details': 'developer/architecture.md'
        - 'Intro to plugin development': 'developer/intro-plugin.md'
        - 'Writing your first plugin': 'developer/writing-first.md'
    - 'Common tasks':
        - 'Manipulating LDAP data': 'developer/ldap-data.md'
    - 'Other topics':
        - 'Plugin development tips': 'developer/tips-development.md'
        - 'Plugin management internals': 'developer/plugin-management-internals.md'
- User Guide : 'user-guide.md'
