# Project information
site_name: Gluu Casa 3.1.6 Docs
site_description: Documentation for Gluu Casa

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
repo_name: GluuFederation/docs-casa-prod
repo_url: https://github.com/GluuFederation/docs-casa-prod/
edit_uri: edit/3.1.6/docs/source
docs_dir: source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.1.6'
    
# Extensions    
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite
- pymdownx.superfences

# Navigation Menu
nav:
- 'Versions':
    - '3.1.6': 'https://gluu.org/docs/casa/3.1.6/'
- ' ': 'https://gluu.org'
- ' ': 'https://gluu.org'
- Home: 'index.md'    
- Administration Guide: 
    - 'Quick Start Guide': 'administration/quick-start.md'
    - 'Installation': 'administration/installation.md'
    - 'About two-factor authentication': 'administration/2fa-basics.md'
    - 'Admin console': 'administration/admin-console.md'   
    - 'Credentials storage': 'administration/credentials-stored.md'
    - 'Custom branding': 'administration/custom-branding.md'
    # - 'Configuration': 'administration/configuration.md'
    - 'URL path customization': 'administration/change-context-path.md'
    - 'Uninstallation and clean up': 'administration/uninstallation.md'
    - 'Localization': 'administration/localization.md'
    - 'Plugins':
        - '2FA Settings': 'plugins/2fa-settings.md'    
        - 'Account linking': 'plugins/account-linking.md'
        - 'Consent Management': 'plugins/consent-management.md'
        - 'Custom Branding': 'plugins/custom-branding.md'
        - 'Write your own plugin': 'plugins/writing-plugins.md'
    - 'FAQ': 'administration/faq.md'
- Developer Guide:
    - 'Intro': 'developer/index.md'
    - 'The basics':
        - 'Architectural details': 'developer/architecture.md'
        - 'Intro to plugin development': 'developer/intro-plugin.md'
        - 'Writing your first plugin': 'developer/writing-first.md'
    - 'Common tasks':
        - 'Working with menus': 'developer/menus.md'
        - 'Adding UI pages': 'developer/ui-pages.md'
        - 'Manipulating LDAP data': 'developer/ldap-data.md'
        - 'Adding REST services': 'developer/rest-services.md'
    - 'Adding authentication methods':
        - 'Introduction': 'developer/authn-methods/index.md'
        - 'Coding authentication logic' : 'developer/authn-methods/authn-logic.md'
        - 'Coding enrollment logic': 'developer/authn-methods/credentials-management.md'
    - 'Other topics':
        - 'Plugin development tips': 'developer/tips-development.md'
        - 'Plugin management internals': 'developer/plugin-management-internals.md'
        - 'FAQ': 'developer/faq.md'
- User Guide : 'user-guide.md'
